MEXC_API_KEY = 'YOUR_MEXC_API_KEY'
MEXC_SECRET_KEY = 'YOUR_MEXC_SECRET_KEY'

COINEX_API_KEY = 'YOUR_COINEX_API_KEY'
COINEX_SECRET_KEY = 'YOUR_COINEX_SECRET_KEY'

SYMBOLS = [
    'BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'SOL/USDT', 'XRP/USDT',
    'ADA/USDT', 'DOGE/USDT', 'AVAX/USDT', 'LINK/USDT', 'DOT/USDT'
]

TIMEFRAME = '5m'
MIN_TRADE_AMOUNT = 1.01

MAX_LEVERAGE = 20
MIN_LEVERAGE = 5

STOP_LOSS_PERCENT = 0.008   
TAKE_PROFIT_PERCENT = 0.012